import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'bharath' at '4/24/17 10:26 PM' with Gradle 2.0
 *
 * @author bharath, @date 4/24/17 10:26 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
       // MainApplication classUnderTest = new MainApplication();
        //assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
